<a href="https://colab.research.google.com/github/apdy10/ML-Basics/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
my_list = [1,2,3]


In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]     #List of Lists

my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2 square brackets shows that this is an 2-d array:

# Python built-in methods to make array

**1. np.arange(s,e,w)**:-  s(start), e(end), w(step size)


arange is a widely used function to quickly create an array. Passing a value 20 to the arange function creates an array with values ranging from 0 to 19.

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

If we only use the arange function, it will output a one-dimensional array. To make it a two-dimensional array, chain its output with the reshape function.

In [8]:
ar = np.arange(20).reshape(4,5)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

**2. All zeros array**

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**3. All ones Array**

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**Linspace** :- take start and end the third argument is no. of evenly spaced points we want between those points

In [15]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

**4. Identity matrix**: A 2-d square matrix, number of rows = number of columns with diagonal elements 1 and other elements being 0

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Creating Random Number Arrays

**np.random.rand()** :- Random numbers form uniform distribution from 0 to 1

In [17]:
np.random.rand(5)

array([0.94077895, 0.50690589, 0.53031771, 0.61105407, 0.04549639])

In [18]:
np.random.rand(5,5)                           # Not tuples as an argument

array([[0.17374192, 0.13666661, 0.71002355, 0.73714756, 0.23178267],
       [0.48088566, 0.91018322, 0.21546283, 0.52215497, 0.85804142],
       [0.48918205, 0.81881442, 0.78422274, 0.22618433, 0.23644463],
       [0.63653238, 0.02580976, 0.43917741, 0.33133575, 0.19367402],
       [0.51354821, 0.30189191, 0.51297133, 0.43340679, 0.52543868]])

**np.random.randn()** :- Random numbers not from the uniform distribution from 0 to 1 but from the standard normal distribution centered around 0

In [19]:
np.random.randn(5)

array([ 1.34693686, -0.87077448, -1.17907667, -2.17311517, -0.07719729])

In [20]:
np.random.randn(5,5)

array([[ 1.47640655,  0.26721978,  0.54954536,  1.18424939,  0.2149241 ],
       [ 0.68892386,  0.9272935 ,  0.43721284,  0.50352836,  1.00142444],
       [-0.09127852, -1.21163944,  0.07905526, -0.05082753,  0.12757426],
       [-1.14805385,  0.66084417, -2.11131979, -2.31497428, -0.05694096],
       [-0.74287706, -1.17936625,  0.66567139,  1.57596419,  3.51877808]])

**np.random.randint()** :- randint(low,high,size)

generates random integer between low and high(low is inclusive and high is exclusive) third argument size gives no. of integers we want between them

In [21]:
np.random.randint(1,10) #default size is 1

6

In [22]:
np.random.randint(1,100,5)

array([ 2, 84, 89,  2, 44])

**Concept of Reshaping**

In [23]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
rearr = np.random.randint(0,50,10)
rearr

array([ 7, 35, 28, 32, 42,  0, 42, 11, 27, 29])

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
rearr

array([ 7, 35, 28, 32, 42,  0, 42, 11, 27, 29])

In [27]:
rearr.max()

42

In [28]:
rearr.min()

0

We can also find the index value at which minimum and maximum value is present using argmax() and argmin()

In [29]:
rearr.argmax()

4

In [30]:
rearr.argmin()

5

In [31]:
arr.shape

(25,)

In [32]:
arr = arr.reshape(5,5)

In [33]:
arr.shape

(5, 5)

In [34]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr.dtype

dtype('int64')

Instead of using np.random.randint() we can also import and then use it as seen below

In [36]:
from numpy.random import randint

In [37]:
randint(2,10)

9

# Numpy array indexing

Index starts from 0

In [38]:
import numpy as np

In [39]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[8]

8

In [41]:
arr[1:5]  #start at index 1 to index 4

array([1, 2, 3, 4])

In [42]:
arr[0:5]   #start at index 0 to index 4

array([0, 1, 2, 3, 4])

In [43]:
arr[:6]    #Similar to arr[0:6] print everything till index 6 from start

array([0, 1, 2, 3, 4, 5])

In [44]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [45]:
arr[5:]    #print everything beyond index 5

array([ 5,  6,  7,  8,  9, 10])

In [48]:
arr[0:5] = 100 #broadcast 100 to index 4

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [50]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
slice_of_arr = arr[0:6]  #get that chunk of array

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [54]:
slice_of_arr[:] = 99 #grabbing everything we have and brodacasting 99 to it

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [55]:
arr   # If I call back the array the value 99 gets into the original one also

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

data is not copied it is just a view to the original array. The reason why nummpy does that is to avoid memory issues with very large arrays meaning numpy is not automatically set copies for arrays. If you originally want a copy not a reference to original array we can specifically specify copy

In [56]:
arr_copy = arr.copy()

In [59]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [58]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr_copy[:] = 100

In [61]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [62]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

The original array is not affected 

**Indexing in 2d Array**

In [63]:
import numpy as np

In [65]:
arr_2d = np.array([[5,10,15], [20,25,30],[35,40,45]])

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [67]:
arr_2d[0][0] #Element in first row and first column

5

In [68]:
arr_2d[0]

array([ 5, 10, 15])

In [69]:
arr_2d[2][1]

40

In [71]:
arr_2d[2,1]

40

Let's assume you don't want single element but want chunks of array for instance you want submatrices from this matrix

In [72]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [73]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [74]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

Conditional Selection from array

In [76]:
arr= np.arange(1,11)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr>5    #Gets true and false values based on the comparison

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [79]:
bool_arr = arr>5

bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [80]:
arr[bool_arr]   #gets the values where boolean values are true

array([ 6,  7,  8,  9, 10])

In [81]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [82]:
arr[arr<3]

array([1, 2])

In [85]:
arr_2d = np.arange(50).reshape(5,10)

arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [87]:
arr_2d[1:2,3:5]

array([[13, 14]])


# Numpy Operations
1. Array with Array
2. Array with scalars
3. Universal Array functions

In [88]:
import numpy as np

In [89]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [91]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [92]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [93]:
arr +100 #add 100 to every element of Array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [94]:
arr*100  #multiply 100 to every element of Array

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [95]:
0/0

ZeroDivisionError: ignored

In [97]:
arr/arr  #since the first element of array is 0 it becomes 0/0 in case of nunmpy it throws a warning not an error

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [98]:
1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [99]:
arr**2            #Exponents

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

**Universal Array Function**

In [100]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [101]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [103]:
np.max(arr)

10

In [104]:
arr.max()

10

In [105]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [106]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])